### ISSUE TITLE
Defect charge states

### ISSUE THREAD

**Issue by ireaml** [materialsproject/pymatgen-analysis-defects#36] opened 2022-09-27 16:22 UTC
Hello! Great package!

@kavanase and I are working on refactoring our [defect structure package](https://github.com/SMTG-UCL/ShakeNBreak) to use the new `Defect` class for compatibility with `pymatgen-analysis-defects`. 
For this, it would be helpful if the `Defect` class had a `charges` attribute where the user can customise the charge states of the defect (e.g. by default, it could be `0` or the result of `.get_charge_states()` but can also be customised by the user).  
Alternatively,  the `Interstitial`/`Vacancy`/`Substitution` classes could inherit from `Defect` or `DefectSpecies` (modified `Defect` class with `charges` attribute) depending on if the charges were defined. 

What do you think is the best approach?

Thanks!

**Comment by jmmshn** [comment] 2022-09-29 16:17
Hi @ireaml, thanks for the suggestion!
So the `Defect` objects themselves do not have the charge state by design since they should be defined before concrete charge states are decided.

The `Defect` object is kept as structural-only since they are really meant to help sort and filter the finished calculations.

I think the best approach here is to have a core object that you need for your particular purpose that contains the `Defect` as one of the attributes as I have here for formation energy calculations:
https://github.com/materialsproject/pymatgen-analysis-defects/blob/0790425bb7fbaaa51d45a77dd20160094a1fe7fe/pymatgen/analysis/defects/thermo.py#L33-L49

**Comment by jmmshn** [comment] 2022-10-07 17:06
@ireaml So I thought about this more and I think my earlier statement is incorrect.
Your suggestion for adding some kind of internal list of of possible charge states should go in the main `Defect` object.
I will add this feature as a PR ASAP. 
Thanks again for the suggesetion!

**Comment by jmmshn** [comment] 2022-10-07 18:28
@ireaml, the changes have been merged.  Will close this now. 
Thanks again!

**Closed by jmmshn** 2022-10-07 18:28 UTC
